// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class GreQuestions : MonoBehaviour
{
	public TextAsset file;

	void Start(){
		Load(file);
	}

	public class Row
	{
		public string Word;
		public string Meaning;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.Word = grid[i][0];
			row.Meaning = grid[i][1];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_Word(string find)
	{
		return rowList.Find(x => x.Word == find);
	}
	public List<Row> FindAll_Word(string find)
	{
		return rowList.FindAll(x => x.Word == find);
	}
	public Row Find_Meaning(string find)
	{
		return rowList.Find(x => x.Meaning == find);
	}
	public List<Row> FindAll_Meaning(string find)
	{
		return rowList.FindAll(x => x.Meaning == find);
	}

}